name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: trrr
      run: tree

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: dev_artifact
        path: ./app/build/outputs/apk/debug/

    - name: Generate DOKKA
      run: ./gradlew dokkaHtml

    - name: Deploy API documentation to Github Pages
      if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
      uses: ps-ovsyanka/GoogleSearchApp@docs
      with:
        branch: gh-pages
        folder: build/dokka/html
        target-folder: docs
