name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Deploy to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2
      with:
        app_id: ${{ secrets.FIREBASE_APP_ID }}
        api_key: ${{ secrets.FIREBASE_API_KEY }}
        groups: 'test-group'
        release_notes_file: 'app/release_notes.txt'
        apk_path: 'app/build/outputs/apk/debug/app-debug.apk'
